#!/bin/bash
echo "Hello Codecademy!"
index=3
#PATH=~/bin:$PATH
#chmod +x script.sh
if [ $index -lt 5 ]
then
  echo $index
else
  echo 5
fi

while [ $index -lt 5 ]
do
  echo $index
  index=$((index + 1))
done
index=0

until [ $index -eq 5 ]
do
  echo $index
  index=$((index + 1))
done
#Equal: -eq
#Not equal: -ne
#Less than or equal: -le
#Less than: -lt
#Greater than or equal: -ge
#Greater than: -gt
#Is null: -z
#Equal: ==
#Not equal: !=
#strings in quotes best practice
#if [ "$foo" == "$bar"]
#!/bin/bash
first_greeting="Nice to meet you!"
later_greeting="How are you?"
greeting_occasion=1
if [ $greeting_occasion -lt 1 ]
then
  echo $first_greeting
else
  echo $later_greeting
fi
paragraph="list of words, looks like a string to me!"
for word in $paragraph
do
  echo $word
done

while [ $greeting_occasion -lt 3 ]
do
if [ $greeting_occasion -lt 1 ]
then
  echo $first_greeting
else
  echo $later_greeting
fi
  greeting_occasion=$((greeting_occasion + 1))
done


#echo "Guess a number"
#read number
#echo "You guessed $number"

#$1, $2
#for color in "$@"
#do
#  echo $color
#done
#./saycolors red green blue
files=/home/kevin/codefizz/*
for file in $files
do
  echo $file
done


first_greeting="Nice to meet you!"
later_greeting="How are you?"
greeting_occasion=0
echo "How many times should I greet?"
read greeting_limit
while [ $greeting_occasion -lt $greeting_limit ]
do
  if [ $greeting_occasion -lt 1 ]
  then
    echo $first_greeting
  else
    echo $later_greeting
  fi
  greeting_occasion=$((greeting_occasion + 1))
done
#for environment or commandline
alias saycolors='./saycolors.sh'
alias saycolors='./saycolors.sh "green"'
alias greet3='./script.sh 3'
